source 'https://rubygems.org'

gem 'rails', '3.2.2'
gem 'haml-rails', '0.3.4'
gem 'sorcery', '0.7.7'
gem 'decent_exposure', '1.0.2'
gem 'aws-sdk', '1.3.4'
gem 'paperclip', '2.6.0'

group :assets do
  gem 'jquery-rails'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'sqlite3'
  gem 'rspec-rails', '2.9.0'
end

group :production do
  gem 'pg'
end

